// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('test', function() {
    this.timeout(30000)
    let driver
    let vars
    beforeEach(async function() {
        driver = await new Builder().forBrowser('chrome').build()
        vars = {}
    })
    afterEach(async function() {
        await driver.quit();
    })
    async function waitForWindow(timeout = 2) {
        await driver.sleep(timeout)
        const handlesThen = vars["windowHandles"]
        const handlesNow = await driver.getAllWindowHandles()
        if (handlesNow.length > handlesThen.length) {
            return handlesNow.find(handle => (!handlesThen.includes(handle)))
        }
        throw new Error("New window did not appear before timeout")
    }
    it('test-test', async function() {
        await driver.get("http://localhost:3000/")
        await driver.manage().window().setRect({ width: 1920, height: 1053 })
        await driver.findElement(By.css(".App-header")).click()
        vars["windowHandles"] = await driver.getAllWindowHandles()
        await driver.findElement(By.linkText("Learn React")).click()
        vars["win6040"] = await waitForWindow(2000)
        await driver.switchTo().window(vars["win6040"])
    })
})